export const authoringDocs = [
  {
    name: 'elems-agent-guide',
    uri: 'elems://docs/agent-guide',
    title: 'ELEMS MCP Agent Guide',
    description: 'Small universal safety and workflow rules; excludes task-specific authoring detail.',
    file: 'AGENT_GUIDE.md',
  },
  {
    name: 'elems-docs-index',
    uri: 'elems://docs/index',
    title: 'ELEMS Authoring Documentation Index',
    description: 'Cheap routing index for choosing only the authoring resources needed by the current task.',
    file: 'docs/index.md',
  },
  {
    name: 'elems-docs-elements',
    uri: 'elems://docs/elements',
    title: 'ELEMS Elements and Safe Targeting',
    description: 'Element trees, domType, mdid, content, attributes, ownership, mutability, and safe target selection.',
    file: 'docs/elements.md',
  },
  {
    name: 'elems-docs-styling',
    uri: 'elems://docs/styling',
    title: 'ELEMS Styling and Tailwind',
    description: 'Class mutations, responsive Tailwind composition, JIT constraints, overflow prevention, and visual QA.',
    file: 'docs/styling-tailwind.md',
  },
  {
    name: 'elems-docs-pages',
    uri: 'elems://docs/pages',
    title: 'ELEMS Pages, Drafts, and Publication',
    description: 'Page creation, page-owned edits, CAS, drafts, previews, publishing, and destructive replacement safety.',
    file: 'docs/pages-and-drafts.md',
  },
  {
    name: 'elems-docs-templates',
    uri: 'elems://docs/templates',
    title: 'ELEMS Templates and Ownership',
    description: 'Effective templates, shared layout, page/template/prefab ownership, scoped mutations, and publication.',
    file: 'docs/templates-and-ownership.md',
  },
  {
    name: 'elems-docs-functions',
    uri: 'elems://docs/functions',
    title: 'ELEMS Runtime Functions',
    description: 'Public functionType/functionData model, allowlist, placement, constraints, and dedicated tools.',
    file: 'docs/functions.md',
  },
  {
    name: 'elems-docs-commands',
    uri: 'elems://docs/commands',
    title: 'ELEMS Commands and Runtime Expressions',
    description: 'Allowlisted runtime values, loops, conditions, parameters, scope, and common mistakes.',
    file: 'docs/commands-runtime.md',
  },
  {
    name: 'elems-docs-media',
    uri: 'elems://docs/media',
    title: 'ELEMS Media',
    description: 'Public media discovery/upload, canonical references, supported formats, accessibility, and limitations.',
    file: 'docs/media.md',
  },
  {
    name: 'elems-docs-localization',
    uri: 'elems://docs/localization',
    title: 'ELEMS Localization',
    description: 'Website/page locales, exact locale values, fallback, selectors, routes, drafts, and publication.',
    file: 'docs/localization.md',
  },
  {
    name: 'elems-docs-forms',
    uri: 'elems://docs/forms',
    title: 'ELEMS Forms and Interaction',
    description: 'Forms, auth/account presets, links, buttons, passive embeds, owned JavaScript, and accessibility.',
    file: 'docs/forms-and-interaction.md',
  },
  {
    name: 'elems-docs-content',
    uri: 'elems://docs/content',
    title: 'ELEMS Generic Content Primitives',
    description: 'PostIdentifier, MdPost, generic rendering, grants, and protected resource assets.',
    file: 'docs/content-primitives.md',
  },
  {
    name: 'elems-docs-ecommerce',
    uri: 'elems://docs/ecommerce',
    title: 'ELEMS Ecommerce Authoring',
    description: 'Products, variants, pricing, product bindings, cart/checkout/orders, promotions, and grants.',
    file: 'docs/ecommerce.md',
  },
  {
    name: 'elems-docs-website-creation',
    uri: 'elems://docs/website-creation',
    title: 'ELEMS Website Selection and Creation',
    description: 'Normal-user website inventory, account-owned creation, selection, and next-step context.',
    file: 'docs/website-creation.md',
  },
]
